### ISSUE TITLE
@contextmanager in Guide to Using Databases with Python Postgres, SQLAlchemy, and Alembic

### ISSUE THREAD

**Issue by roschel** [LearnDataSci/blog-post-resources#12]
Hi Brendan, how are you doing?

Regarding the article **Guide to Using Databases with Python Postgres, SQLAlchemy, and Alembic**, I applied this in my project:
```python
from contextlib import contextmanager

@contextmanager
def session_scope():
    session = Session()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
```
but now, when I try to query something to pass to my service layer, I'm getting this error:
`sqlalchemy.orm.exc.DetachedInstanceError: Instance <Driver at 0x7f5ce0464c40> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/14/bhk3)`

this is my code:
```python
def find_all(model, skip: int = 0, limit: int = 0):
    with session_scope() as db:
        r = db.query(model).offset(skip).limit(limit).all()
        return r
```

Can you help me to understand whats is happing?

**Comment by BrendanMartin** [comment]
Hi @roschel,

Are you attempting to access any relationship data from `r`? Once you return `r`, the session is closed, so lazy-loaded data (like from relationships) can't be accessed.

**Comment by roschel** [comment]
There is no relationship in the model I'm trying to query. So, since the data can't be access, I'm not suppose to use the session_scope for queries? Only to persist the model to database?

**Comment by BrendanMartin** [comment]
My projects almost always use this kind of context manager setup for querying.
See this StackOverflow answer: https://stackoverflow.com/questions/8253978/sqlalchemy-get-object-not-bound-to-a-session
I often used expunge_all() for this type of situation.
