### ISSUE TITLE
Error in path to read.csv

### ISSUE THREAD

**Issue by isaacguerreir** [LearnDataSci/blog-post-resources#3]
In this part:

`unemployment = pd.read_csv('/Users/tdobbins/Downloads/hpi/unemployment-macro.csv')`

Actually the correct path is:

`unemployment = pd.read_csv('/Users/tdobbins/Downloads/hpi/unemployment.csv')`

**Comment by BrendanMartin** [comment]
Thanks for letting me know. I'll get that fixed.
