### ISSUE TITLE
Yahoo Finance not working 

### ISSUE THREAD

**Issue by simonzcaiman** [LearnDataSci/blog-post-resources#5]
Hi,

I tried your yahoo finance api notebook example. Apparently, the yahoo fetch is not working anymore. It says "
RemoteDataError: No data fetched using 'YahooDailyReader'". Could you please check it out? thanks

**Comment by BrendanMartin** [comment]
@simonzcaiman Yes, unfortunately the Yahoo API has changed and the Pandas connection no longer works. We have a new post coming out that'll use a different method and the old post will be updated.
